// Generated by scripts/prepare-brain-2d.mjs — do not edit by hand.
export const BRAIN2D_PATH = "/image/brain-2d.509be6b281.bin";

// Section anchors (brainAsset.ts), projected to the same side view and
// normalized to [0,1] over the brain's width and height.
export const ANCHORS_2D: readonly [number, number][] = [[0.4925,0.1967],[0.166,0.4698],[0.2231,0.6141],[0.3758,0.7066],[0.8169,0.3922],[0.9101,0.6936]];
