import Link from "next/link";
import { Suspense, cache } from "react";
import { client } from "../../../../../sanity/lib/client";
import {
	DEFAULT_LANGUAGE,
	localizedPath,
	type Language,
} from "../../../../../entities/i18n";
import { SITE_URL } from "../../../../../entities/site";
import { toJsonLdScript } from "../../../../../entities/jsonLd";
import { formatPostDate } from "../../../../src/components/Blog/postDate";
import { getDict } from "../../../../src/i18n/dict";
import { alternates } from "../../../../src/i18n/meta";
import { notFound } from "next/navigation";
import { postBySlugQuery, postsQuery } from "../../../../../sanity/lib/queries";
import ReadingProgress from "../../../../src/components/Blog/ReadingProgress";
import PostBody from "../../../../src/components/Blog/PostBody";
import PostCover from "../../../../src/components/Blog/PostCover";
import { cleanTitle } from "../../../../src/components/Blog/title";
import {
	extractExcerpt,
	type PortableTextBlock,
} from "../../../../src/components/Blog/excerpt";

interface Post {
	_updatedAt?: string;
	title: string;
	publishedAt: string;
	body?: PortableTextBlock[];
	markdownBody?: string;
	tags?: string[];
}

interface PageProps {
	params: Promise<{ slug: string; lang: Language }>;
}

const BASE_URL = SITE_URL;

const getPost = cache(
	(slug: string): Promise<Post | null> => client.fetch(postBySlugQuery, { slug }),
);

type PostSummary = { slug: string; title: string };

const getAllPosts = cache(
	(): Promise<PostSummary[]> => client.fetch(postsQuery),
);

export async function generateStaticParams() {
	const posts: { slug: string }[] = await client.fetch(
		`*[_type=="post"]{ "slug": slug.current }`,
	);
	return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: PageProps) {
	const { slug, lang } = await params;
	const post = await getPost(slug);
	if (!post) return { title: "Post not found" };

	const description = extractExcerpt(post);
	const title = cleanTitle(post.title);

	return {
		title: `${title} — Joaquín Mussi`,
		description,
		// The blog lives in Sanity in Spanish only: don't declare an "en"
		// hreflang with no real translation behind it (see proxy.ts).
		alternates: alternates(lang, `/blog/${slug}`, false),
		// No `images`: the card is set by this same folder's
		// opengraph-image.tsx, and declaring the field here — even as [] —
		// would win over the file and leave the post with no image when
		// shared. Same treatment as projects/[slug].
		openGraph: {
			title,
			description,
			url: `${BASE_URL}${localizedPath(DEFAULT_LANGUAGE, `/blog/${slug}`)}`,
			type: "article",
			publishedTime: post.publishedAt,
			authors: ["Joaquín Mussi"],
		},
		twitter: {
			card: "summary_large_image",
			title,
			description,
		},
	};
}

async function PostContent({ slug, lang }: { slug: string; lang: Language }) {
	const post = await getPost(slug);

	if (!post) return notFound();

	const d = getDict(lang);
	const title = cleanTitle(post.title);
	const breadcrumbJsonLd = {
		"@context": "https://schema.org",
		"@type": "BreadcrumbList",
		itemListElement: [
			{ "@type": "ListItem", position: 1, name: "Joaquín Mussi", item: BASE_URL },
			{
				// /blog, not /#step-4: the breadcrumb has to point to a URL
				// that's indexable on its own. The home's section 4 is an
				// anchor inside another page, not the post's parent.
				"@type": "ListItem",
				position: 2,
				name: d.blog.title,
				item: `${BASE_URL}${localizedPath(DEFAULT_LANGUAGE, "/blog")}`,
			},
			{
				"@type": "ListItem",
				position: 3,
				name: title,
				item: `${BASE_URL}${localizedPath(DEFAULT_LANGUAGE, `/blog/${slug}`)}`,
			},
		],
	};

	const jsonLd = {
		"@context": "https://schema.org",
		"@type": "BlogPosting",
		headline: title,
		description: extractExcerpt(post),
		author: {
			"@type": "Person",
			name: "Joaquín Mussi",
			url: BASE_URL,
		},
		publisher: {
			"@type": "Person",
			name: "Joaquín Mussi",
			url: BASE_URL,
		},
		url: `${BASE_URL}${localizedPath(DEFAULT_LANGUAGE, `/blog/${slug}`)}`,
		datePublished: post.publishedAt ?? undefined,
		// Sanity's _updatedAt: this used to repeat publishedAt, meaning it
		// declared to Google that no post was ever edited — exactly the
		// signal it uses to decide whether it's worth re-crawling it.
		dateModified: post._updatedAt ?? post.publishedAt ?? undefined,
		// The blog's content is Spanish, always — not whatever the route declares.
		inLanguage: DEFAULT_LANGUAGE,
		// No `image`: the cover is now generated by opengraph-image.tsx, and
		// Next gives the file its own suffix and hash
		// (…/opengraph-image-1lndgs?fb20b39…) that can't be written by hand
		// — building the URL here produced a 404 inside the structured data.
		// The card still travels in og:image, which is where Google picks it
		// up from. Same approach as projects/[slug]: an incomplete schema is
		// better than a made-up one.
	};

	const allPosts = await getAllPosts();
	const idx = allPosts.findIndex((p) => p.slug === slug);
	const olderPost = idx >= 0 ? allPosts[idx + 1] : undefined;
	const newerPost = idx >= 0 && idx > 0 ? allPosts[idx - 1] : undefined;

	return (
		<>
		<article id='post-article' className='enter enter-2 membrane marks relative px-7 py-9 md:px-14 md:py-14'>
			<script
				type='application/ld+json'
				dangerouslySetInnerHTML={{ __html: toJsonLdScript(jsonLd) }}
			/>
			<script
				type='application/ld+json'
				dangerouslySetInnerHTML={{ __html: toJsonLdScript(breadcrumbJsonLd) }}
			/>
			<h1 className='m-0 mb-4 text-3xl leading-tight md:text-5xl'>
				{title}
			</h1>

			{post.publishedAt && (
				<p className='m-0 mb-8 font-mono text-xs text-synapse'>
					{formatPostDate(post.publishedAt, lang)}
				</p>
			)}

			{/* The cover comes from the site's own tissue, not an image bank
			(see PostCover.tsx). It's SVG in the server's HTML: there's no
			longer an image to download, so there's also no need to fight the
			LCP with `priority` and `sizes` like with the previous cover. */}
			<PostCover slug={slug} tagCount={post.tags?.length ?? 0} />

			<PostBody body={post.body} markdownBody={post.markdownBody} />

			{post.tags && post.tags.length > 0 && (
				<div className='mt-10 flex flex-wrap gap-2'>
					{post.tags.map((tag) => (
						<Link
							key={tag}
							href={localizedPath(lang, `/blog/tag/${tag}`)}
							className='border border-synapse/50 px-2.5 py-1 font-mono text-[11px] text-synapse transition-colors duration-200 ease-impulse hover:border-impulse hover:text-impulse'
						>
							{tag}
						</Link>
					))}
				</div>
			)}
		</article>

		{(olderPost || newerPost) && (
			<nav
				aria-label={`${d.blog.previous} / ${d.blog.next}`}
				className='grid grid-cols-1 gap-4 border-t border-synapse/20 pt-6 sm:grid-cols-2'
			>
				<div>
					{olderPost && (
						<Link
							href={localizedPath(lang, `/blog/${olderPost.slug}`)}
							className='group flex flex-col gap-1'
						>
							<span className='font-mono text-[10px] uppercase tracking-[.14em] text-synapse'>
								← {d.blog.previous}
							</span>
							<span className='font-label text-sm text-myelin transition-colors duration-200 ease-impulse group-hover:text-impulse'>
								{cleanTitle(olderPost.title)}
							</span>
						</Link>
					)}
				</div>
				<div className='sm:text-right'>
					{newerPost && (
						<Link
							href={localizedPath(lang, `/blog/${newerPost.slug}`)}
							className='group flex flex-col gap-1 sm:items-end'
						>
							<span className='font-mono text-[10px] uppercase tracking-[.14em] text-synapse'>
								{d.blog.next} →
							</span>
							<span className='font-label text-sm text-myelin transition-colors duration-200 ease-impulse group-hover:text-impulse'>
								{cleanTitle(newerPost.title)}
							</span>
						</Link>
					)}
				</div>
			</nav>
		)}
		</>
	);
}

function PostSkeleton() {
	return (
		<div className='membrane px-7 py-9 md:px-14 md:py-14'>
			<div className='h-8 w-2/3 bg-synapse/15 mb-3' />
			<div className='h-8 w-1/2 bg-synapse/15 mb-3' />
			<div className='h-3 w-36 bg-synapse/15 mb-8' />
			<div className='w-full h-64 md:h-96 bg-synapse/15 mb-10' />
			<div className='max-w-3xl flex flex-col gap-3'>
				{Array.from({ length: 5 }).map((_, i) => (
					<div
						key={i}
						className={`h-4 bg-synapse/15 ${i % 4 === 3 ? "w-2/3" : "w-full"}`}
					/>
				))}
				<div className='mt-6 flex flex-col gap-3'>
					<div className='h-4 w-full bg-synapse/15' />
					<div className='h-4 w-5/6 bg-synapse/15' />
					<div className='h-4 w-11/12 bg-synapse/15' />
					<div className='h-4 w-3/4 bg-synapse/15' />
				</div>
			</div>
			<div className='mt-10 flex gap-2'>
				<div className='h-6 w-16 bg-synapse/15' />
				<div className='h-6 w-20 bg-synapse/15' />
			</div>
		</div>
	);
}

export default async function PostPage({ params }: PageProps) {
	const { slug, lang } = await params;
	const d = getDict(lang);

	return (
		<main className='nervous-system min-h-screen px-5 py-12 md:px-16 md:py-16'>
			<ReadingProgress targetId='post-article' />
			<div className='mx-auto flex max-w-[760px] flex-col gap-8'>
				<div className='enter enter-1 flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2 border-b border-synapse/20 pb-4'>
					<Link
						href={localizedPath(lang, "/blog")}
						className='inline-flex w-fit items-center gap-2 font-label text-xs font-semibold uppercase tracking-[.12em] text-synapse transition-colors duration-200 ease-impulse hover:text-impulse'
					>
						<svg
							width='11'
							height='11'
							viewBox='0 0 448 512'
							fill='currentColor'
							aria-hidden='true'
						>
							<path d='M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.9 0L7 273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5 9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z' />
						</svg>
						{d.blog.backToBlog}
					</Link>
					<Link
						href={localizedPath(lang, "/")}
						className='font-mono text-[10px] uppercase tracking-[.18em] text-myelin transition-colors duration-200 ease-impulse hover:text-impulse'
					>
						Joaquín Mussi
					</Link>
				</div>

				<Suspense fallback={<PostSkeleton />}>
					<PostContent slug={slug} lang={lang} />
				</Suspense>
			</div>
		</main>
	);
}
